# Generated by Django 2.2.1 on 2019-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('src', models.ImageField(height_field='height', upload_to='photos/%Y/%m/%d/', width_field='width')),
                ('width', models.IntegerField(editable=False, null=True)),
                ('height', models.IntegerField(editable=False, null=True)),
            ],
        ),
    ]
